	INTEGER FUNCTION IBFMS ( R8VAL )

C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    IBFMS
C   PRGMMR: J. ATOR          ORG: NP12       DATE: 2006-11-06
C
C ABSTRACT: THIS FUNCTION TESTS WHETHER THE INPUT VALUE IS EQUIVALENT
C   TO THE BUFR ARCHIVE LIBRARY "MISSING" VALUE.  THE COMPARISON IS
C   MADE USING A FUZZINESS THRESHOLD TO ENSURE THAT REAL NUMBERS ARE
C   NOT TESTED FOR ACTUAL EQUALITY TO EACH OTHER.  THE USE OF INTEGER
C   RETURN CODES ALLOWS THIS FUNCTION TO BE CALLED IN A LOGICAL
C   CONTEXT FROM A CALLING PROGRAM WRITTEN IN C.
C
C PROGRAM HISTORY LOG:
C 2006-11-06  J. ATOR    -- ORIGINAL AUTHOR
C
C USAGE:    IBFMS ( R8VAL )
C   INPUT ARGUMENT LIST:
C     R8VAL    - REAL*8: VALUE TO BE TESTED FOR EQUIVALENCE TO 
C                BUFR ARCHIVE LIBRARY "MISSING" VALUE
C
C   OUTPUT ARGUMENT LIST:
C     IBFMS    - INTEGER: RETURN CODE:
C                0 - R8VAL IS NOT EQUIVALENT TO "MISSING"
C                1 - R8VAL IS EQUIVALENT TO "MISSING"
C
C REMARKS:
C    THIS ROUTINE CALLS:        None
C    THIS ROUTINE IS CALLED BY: 
C                               Normally not called by any application
C                               programs but it could be.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  PORTABLE TO ALL PLATFORMS
C
C$$$

	REAL*8 BMISS
	DATA BMISS / 10E10 /

	REAL*8		R8VAL

C	The following parameter defines the fuzziness threshold to use 
C	when testing for BUFR "missing".

	REAL*8          BDIFD
	PARAMETER       ( BDIFD = 10.0E6 )
C----------------------------------------------------------------------
C----------------------------------------------------------------------

	IF ( ABS ( R8VAL - BMISS ) .LT. BDIFD ) THEN
	    IBFMS = 1
	ELSE
	    IBFMS = 0
	END IF

	RETURN
	END
